version: '3'
services:

  # Yii2 Service
  yii2-app:
    user: "www-data"
    build: ./yii2-app
    container_name: yii2-app
    expose:
      - "9000"
    volumes:
      - ./yii2-app:/var/www/html
    depends_on:
      - auth-api
    environment:
      - YII_ENV=dev
    networks:
      - news-network
  # Nginx Service
  nginx:
    image: "nginx"
    container_name: nginx
    ports:
      - "80:80"
      - "8080:80"
    volumes:
      - ./yii2-app/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - yii2-app
    networks:
      - news-network

  # Auth API Service
  auth-api:
    container_name: auth-api
    build: ./auth-api
    ports:
      - "3001:3000"
    volumes:
      - ./auth-api/src:/usr/src/app/src
    depends_on:
      - storage-api
    environment:
      - NODE_ENV=development
    networks:
      - news-network

  # Storage API Service
  storage-api:
    container_name: storage-api
    build: ./storage-api
    ports:
      - "3002:3000"
    volumes:
      - ./storage-api/src:/usr/src/app/src
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
    networks:
      - news-network

  # MongoDB Service
  mongo:
    container_name: mongo
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - news-network

volumes:
  mongodb_data:

networks:
  news-network:
    driver: bridge