version: '3'

services:
  yii2-app:
    build:
      context: ./yii2-app
    container_name: yii2-app
    expose:
      - "9000"
    environment:
      - YII_ENV=dev
    networks:
      - news-network
    volumes:
      - ./yii2-app:/var/www/html

  auth-api:
    build:
      context: ./auth-api
    container_name: auth-api
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    networks:
      - news-network

  storage-api:
    build:
      context: ./storage-api
    container_name: storage-api
    ports:
      - "3002:3000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
    networks:
      - news-network

  mongo:
    container_name: mongo
    image: "mongo"
    ports:
      - "27017:27017"
    networks:
      - news-network

  nginx:
    image: "nginx"
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./yii2-app:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - yii2-app
    networks:
      - news-network

networks:
  news-network:

volumes:
  mongodb_data:
