version: '3'
services:
  auth-api:
    container_name: auth-api
    build: .
    ports:
      - "3001:3000"
    volumes:
      - ./src:/usr/src/app/src
    environment:
      - NODE_ENV=development
    networks:
      - news-network

networks:
  news-network:
    external: true
