version: '3'
services:
  storage-api:
    container_name: storage-api
    build: .
    ports:
      - "3002:3000"
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
    networks:
      - news-network

  mongo:
    container_name: mongo
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - news-network

volumes:
  mongodb_data:

networks:
  news-network: