version: '3'

services:
  yii2-app:
    build: .
    container_name: yii2-app
    expose:
      - "9000"
    volumes:
      - .:/var/www/html
    environment:
      - YII_ENV=dev
    networks:
      - news-network

networks:
  news-network: